### ISSUE TITLE
latest tag from gleroy/simpaas-api and gleroy/simpaas-op is missing linux/amd64

### ISSUE THREAD

**Issue by deltatree** [leroyguillaume/simpaas#17]
Hi,

I want to try your project, but there are some issues during the deployment:
latest tags from gleroy/simpaas-api and gleroy/simpaas-op are missing linux/amd64

See:
https://hub.docker.com/r/gleroy/simpaas-op/tags
https://hub.docker.com/r/gleroy/simpaas-api/tags

Thanks for your work

Alex

**Comment by leroyguillaume** [comment]
Hello,

I really appreciate your interest in SimPaaS. 

I just pushed a tag [`sha-e71bfd6`](https://hub.docker.com/layers/gleroy/simpaas-op/sha-e71bfd6/images/sha256-6a8d52a1f1386f4d10ccec92945b56fb985660b9d6ca6f7f86df6a11b1328bb9?context=repo) that matches `main`. 

Note that the project is currently a "work in progress", there is no documentation about the API and the UI doesn't exist yet. 

You can use the Helm chart to install SimPaaS in your cluster.

Feedbacks/contributions are appreciated, don't hesitate! 

Guillaume
